# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad329e2dd4a1569354fe1bd8343d95ea22e224dd0767f0ff48e60f6809a60d609471d1c60411428ac5b0ec38059781ff46db1ef6ff9f4e42984e369e9f6d57b9

test:
  secret_key_base: efa9f062c4bdf177faa959d0cf5a9f8fe7b9bcb2e20177195b733a3b5e2810774b51b16929603ae01d32a3b90f27b4de0546ee38b7b1c95b83890afb837b75ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
